heat_template_version: 2013-05-23

description: Staging Environment on Prod Rackspace Account

parameters:

  salt_config_script:
    description: User Data script to configure salt and get it going
    type: string
    default: |
      #!/bin/bash -v
      curl -L https://bootstrap.saltstack.com | sh -s -- -A master1.salt.prod1.crowdrise.io -U -P git 2014.7 2>&1 | tee /var/log/bootstrap.log
      ( salt-call state.highstate || true ) | tee -a /var/log/bootstrap.log
      ( salt-call state.highstate || true ) | tee -a /var/log/bootstrap.log
      ( salt-call state.highstate || true ) | tee -a /var/log/bootstrap.log
      reboot

  sphinx_name:
    description: base name for the web server instances
    type: string
    default: sphinx

  sphinx_name_end:
    description: base name for the web server instances
    type: string
    default: .search.stage1.crowdrise.io

  sphinx_image:
    type: string
    label: sphinx Server OS Image
    description: Operating system for VM
    default: 'Ubuntu 14.10 (Utopic Unicorn) (PVHVM)'
    constraints:
      -
        allowed_values:
          - 'Ubuntu 14.10 (Utopic Unicorn) (PVHVM)'
          - 'Ubuntu 14.10 (Utopic Unicorn)'
          - 'Ubuntu 14.04 LTS (Trusty Tahr) (PVHVM)'
          - 'Ubuntu 14.04 LTS (Trusty Tahr)'
          - 'Ubuntu 12.04 LTS (Precise Pangolin) (PVHVM)'
          - 'Ubuntu 12.04 LTS (Precise Pangolin)'

  sphinx_flavor:
    type: string
    label: Image Flavor
    description: sphinx Server VM Flavor
    default: '8 GB Performance'
    constraints:
      -
        allowed_values:
          - '4GB Standard Instance'
          - '8GB Standard Instance'
          - '3.75 GB Compute v1'
          - '7.5 GB Compute v1'
          - '4 GB General Purpose v1'
          - '4 GB Performance'
          - '8 GB Performance'
          - '15 GB Performance'

  sphinx_number:
    default: 2
    label: 'sphinx Servers'
    type: number
    description: 'Number of sphinx Servers to deploy.'
    constraints:
      -
        range:
          max: 3
          min: 0
        description: 'Must be between 0 and 3 servers'


  redis_name:
    description: base name for the web server instances
    type: string
    default: redis

  redis_name_end:
    description: base name for the web server instances
    type: string
    default: .cache.stage1.crowdrise.io

  redis_image:
    type: string
    label: Redis Server OS Image
    description: Operating system for VM
    default: 'Ubuntu 14.10 (Utopic Unicorn) (PVHVM)'
    constraints:
      -
        allowed_values:
          - 'Ubuntu 14.10 (Utopic Unicorn) (PVHVM)'
          - 'Ubuntu 14.10 (Utopic Unicorn)'
          - 'Ubuntu 14.04 LTS (Trusty Tahr) (PVHVM)'
          - 'Ubuntu 14.04 LTS (Trusty Tahr)'
          - 'Ubuntu 12.04 LTS (Precise Pangolin) (PVHVM)'
          - 'Ubuntu 12.04 LTS (Precise Pangolin)'

  redis_flavor:
    type: string
    label: Image Flavor
    description: Redis Server VM Flavor
    default: '8 GB Performance'
    constraints:
      -
        allowed_values:
          - '4GB Standard Instance'
          - '8GB Standard Instance'
          - '3.75 GB Compute v1'
          - '7.5 GB Compute v1'
          - '4 GB General Purpose v1'
          - '4 GB Performance'
          - '8 GB Performance'
          - '15 GB Performance'

  redis_number:
    default: 2
    label: 'Redis Servers'
    type: number
    description: 'Number of Redis Servers to deploy.'
    constraints:
      -
        range:
          max: 3
          min: 0
        description: 'Must be between 0 and 3 servers'

  web_name:
    description: base name for the web server instances
    type: string
    default: http

  web_name_end:
    description: base name for the web server instances
    type: string
    default: .www.stage1.crowdrise.io

  web_image:
    type: string
    label: Apache Server OS Image
    description: Operating system for VM
    default: 'Ubuntu 14.04 LTS (Trusty Tahr) (PVHVM)'
    constraints:
      -
        allowed_values:
          - 'Ubuntu 14.10 (Utopic Unicorn) (PVHVM)'
          - 'Ubuntu 14.10 (Utopic Unicorn)'
          - 'Ubuntu 14.04 LTS (Trusty Tahr) (PVHVM)'
          - 'Ubuntu 14.04 LTS (Trusty Tahr)'
          - 'Ubuntu 12.04 LTS (Precise Pangolin) (PVHVM)'
          - 'Ubuntu 12.04 LTS (Precise Pangolin)'

  web_flavor:
    type: string
    label: VM Flavor
    description: Apache Server VM Flavor
    default: '15 GB Performance'
    constraints:
      -
        allowed_values:
          - '4GB Standard Instance'
          - '8GB Standard Instance'
          - '3.75 GB Compute v1'
          - '7.5 GB Compute v1'
          - '4 GB General Purpose v1'
          - '4 GB Performance'
          - '15 GB Performance'

  web_numbers:
    default: 2
    label: 'Apache Servers'
    type: number
    description: 'Number of Apache Servers to deploy.'
    constraints:
      -
        range:
          max: 10
          min: 0
        description: 'Must be between 0 and 10 servers'

resources:
  web_lb:
    type: "Rackspace::Cloud::LoadBalancer"
    properties:
      name:
        str_replace:
          template: $front$back
          params:
            $front: { get_param: web_name }
            $back: { get_param: web_name_end }
      nodes: []
      port: 443
      protocol: HTTPS
      algorithm: ROUND_ROBIN
      virtualIps:
      - type: PUBLIC
        ipVersion: IPV4
      metadata:
        rax-heat: { get_param: "OS::stack_id" }
        stack-name: { get_param: "OS::stack_name" }
  webservers:
    type: 'Rackspace::AutoScale::Group'
    properties:
      groupConfiguration:
        name: 
          str_replace:
            template: $front-$back
            params:
              $front: { get_param: web_name }
              $back: { get_param: web_name_end }
        cooldown: 60
        minEntities: 2
        maxEntities: 10
        metadata:
          cool_factor: "50"
      launchConfiguration:
        type: launch_server
        args:
          server:
            name:
              str_replace:
                template: $front%index%$back
                params:
                  $front: { get_param: web_name }
                  $back: { get_param: web_name_end }
            flavorRef:
              get_param: web_flavor
            imageRef:
              get_param: web_image
            key_name: hop-2048
            user_data: { get_param: salt_config_script }
            metadata:
              rax-heat: { get_param: "OS::stack_id" }
              stack-name: { get_param: "OS::stack_name" }
              hotness_factor: "100"
          loadBalancers:
            -
              loadBalancerId: { get_resource: web_lb }
              port: 443
  sphinxservers:
    type: 'OS::Heat::ResourceGroup'
    properties:
      count:
        get_param: sphinx_number
      resource_def:
        type: 'Rackspace::Cloud::Server'
        properties:
          flavor:
            get_param: sphinx_flavor
          name:
            str_replace:
              template: $front%index%$back
              params:
                $front: { get_param: sphinx_name }
                $back: { get_param: sphinx_name_end }
          key_name: hop-2048
          image:
            get_param: sphinx_image
          user_data: { get_param: salt_config_script }
          metadata:
            rax-heat: { get_param: "OS::stack_id" }
            stack-name: { get_param: "OS::stack_name" }
  sphinx_lb:
    type: "Rackspace::Cloud::LoadBalancer"
    depends_on:
      - sphinxservers
    properties:
      name:
        str_replace:
          template: $front$back
          params:
            $front: { get_param: sphinx_name }
            $back: { get_param: sphinx_name_end }
      nodes:
      - addresses: [ { get_attr: [sphinxservers, privateIPv4] } ]
        port: 9312
        condition: enabled
      healthMonitor:
        type: CONNECT
        delay: 10
        timeout: 5
        attemptsBeforeDeactivation: 3
      port: 9312
      protocol: TCP_CLIENT_FIRST
      algorithm: ROUND_ROBIN
      virtualIps:
      - type: SERVICENET
        ipVersion: IPV4
      metadata:
        rax-heat: { get_param: "OS::stack_id" }
        stack-name: { get_param: "OS::stack_name" }

  redisservers:
    type: 'OS::Heat::ResourceGroup'
    properties:
      count:
        get_param: redis_number
      resource_def:
        type: 'Rackspace::Cloud::Server'
        properties:
          flavor:
            get_param: redis_flavor
          name:
            str_replace:
              template: $front%index%$back
              params:
                $front: { get_param: redis_name }
                $back: { get_param: redis_name_end }
          key_name: hop-2048
          image:
            get_param: redis_image
          user_data: { get_param: salt_config_script }
          metadata:
            rax-heat: { get_param: "OS::stack_id" }
            stack-name: { get_param: "OS::stack_name" }

outputs:
  public_ips_redis:
    description: 'Sphinx Internal IPs'
    value:
      get_attr:
        - redisservers
        - publicIPv4
  public_ips_redis:
    description: 'Redis Internal IPs'
    value:
      get_attr:
        - redisservers
        - publicIPv4
