parameter_groups:
  -
  parameters:
    - image
    - dash_flavor
  label: 'DashBoard Settings'
    -
  parameters:
    - web_flavor
    - number_of_web
  label: 'Web Settings'
      -
  parameters:
    - network_range
  label: 'Network Config'

heat_template_version: 2013-05-23

description: OpenStack Dashboard w/Network

parameters:

  image:
    type: string
    label: Image OS
    description: Operating system for VM
    default: 'Ubuntu 14.10 (Utopic Unicorn) (PVHVM)'
    constraints:
      -
        allowed_values:
          - 'Ubuntu 14.10 (Utopic Unicorn) (PVHVM)'
          - 'Ubuntu 14.10 (Utopic Unicorn)'
          - 'Ubuntu 14.04 LTS (Trusty Tahr) (PVHVM)'
          - 'Ubuntu 14.04 LTS (Trusty Tahr)'
          - 'Ubuntu 12.04 LTS (Precise Pangolin) (PVHVM)'
          - 'Ubuntu 12.04 LTS (Precise Pangolin)'

  dash_flavor:
    type: string
    label: Image Flavor
    description: VM Flavor
    default: '2GB Standard Instance'
    constraints:
      -
        allowed_values:
          - '2GB Standard Instance'
          - '4GB Standard Instance'
          - '8GB Standard Instance'
          - '3.75 GB Compute v1'
          - '2 GB General Purpose v1'
          - '4 GB General Purpose v1'
          - '2 GB Performance'
          - '4 GB Performance'
          - '15 GB Performance'
  network_range:
    default: 192.168.224.0/20
    type: string
    description: 'Private Network'
    label: 'Private Network CIDR'
  number_of_webs:
    default: 2
    label: 'Number of Apache Servers'
    type: number
    description: 'Number of minion servers to deploy.'
    constraints:
      -
        range:
          max: 100
          min: 0
        description: 'Must be between 0 and 100 servers'

resources:
  dashboard:
    type: "Rackspace::Cloud::Server"
    properties:
      flavor: { get_param: instance_flavor }
      image: { get_param: instance_image }
      name: http1.os.dev1.crowdrise.io
      key_name: hop-2014-2048
      user_data: "#!/bin/bash -v\ncurl -L https://bootstrap.saltstack.com | sh -s -- -A master01.salt.dev1.crowdrise.io -U 2>&1 | tee /var/log/bootstrap.log\nsalt-call state.highstate | tee -a /var/log/bootstrap.log\nsalt-call state.highstate | tee -a /var/log/bootstrap.log"
      networks:
        -
          uuid: 00000000-0000-0000-0000-000000000000
        -
          uuid: 11111111-1111-1111-1111-111111111111
        -
          uuid:
            get_resource: devnetwork
  devnetwork:
    type: 'Rackspace::Cloud::Network'
  properties:
    cidr: 10.0.0.0/20
    label: devnetwork
  webservers:
    depends_on: dashboard
    type: 'OS::Heat::ResourceGroup'
    properties:
      count:
        get_param: number_of_webs
      resource_def:
        type: 'Rackspace::Cloud::Server'
        properties:
          flavor:
            get_param: web_flavor
          name: salt-minion%index%
          key_name: 2014-hop-2048
          image:
            get_param: image
          user_data:
            str_replace:
              params:
                '%salt_master%':
                  get_attr:
                    - salt_master_server
                    - networks
                    - devnetwork
                    - 0
              template: "#!/bin/bash\napt-get update\napt-get install python-software-properties -y\nadd-apt-repository ppa:saltstack/salt -y\napt-get update\napt-get install salt-minion -y\nsed -i 's/^#master: salt$/master: %salt_master%/' /etc/salt/minion\n/etc/init.d/salt-minion restart\n"
          networks:
            -
              uuid: 00000000-0000-0000-0000-000000000000
            -
              uuid: 11111111-1111-1111-1111-111111111111
            -
              uuid:
                get_resource: devnetwork

outputs:
  public_ip_dashboard:
    description: Public IP
    value: { get_attr: [dashboard, accessIPv4] }
  private_ip_dashboard:
    description: Private IP
    value: { get_attr: [dashboard, privateIPv4] }
  public_ips_web:
    description: 'Web IPs'
    value:
      get_attr:
        - webservers
        - accessIPv4
